### ISSUE TITLE
Add gnomAD allele frequencies for WGS workflows

### ISSUE THREAD

**Issue by jasonwalker80** [genome/analysis-workflows#284]
Title says it all. See the tumor-only workflow for reusable subworkflows.

**Comment by chrisamiller** [comment]
By default, VEP does not include all the gnomAD AF data for whole genome regions (just has exome AFs). There is a workaround to get the whole genome data described here: https://useast.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad

jwalker says "We have the WGS data downloaded that could be used instead. There are a few parts to that: 
1) get the VCF fixed for b38 much like the exome was 
2) update the WGS ProcessingProfile to use the WGS gnomAD VCF 
3) The annotated VCF tag is `gnomADe`, it's not configurable yet. The plan was to implement `gnomADg` if/when the time came."

**Comment by chrisamiller** [comment]
@apaul7 I know you did a bunch of work on incorporating gnomAD data - Is there more to do here, or can this be closed?

**Comment by apaul7** [comment]
This issue can be closed. I added the VEP custom annotation type allowing users to customize what annotations they would like to use. like in the example wgs yaml:
```
vep_custom_annotations:
- method: 'exact'
  force_report_coordinates: true
  annotation:
    file:
      class: File
      path: exome_workflow/chr17_test_gnomADe.vcf.gz
      secondaryFiles: [{class: File, path: exome_workflow/chr17_test_gnomADe.vcf.gz.tbi}]
    data_format: 'vcf'
    name: 'gnomADe'
    vcf_fields: ['AF','AF_AFR','AF_AMR','AF_ASJ','AF_EAS','AF_FIN','AF_NFE','AF_OTH','AF_SAS']
    gnomad_filter: true
    check_existing: true
```
