### ISSUE TITLE
malformed requirements fields

### ISSUE THREAD

**Issue by chrisamiller** [genome/analysis-workflows#501]
There are a bunch of tools that have docker requirements slapped in like this: 
```
requirements:
    - class: DockerRequirement                                                                                                                                                                                                                                                      dockerPull: "mgibio/bisulfite"
arguments: [
    "--target", {valueFrom: "$(runtime.outdir)/trimmed_read"},
    "--threads", {valueFrom: "$(runtime.cores)"}
]
requirements:
    - class: ResourceRequirement
      ramMin: 16000
      tmpdirMin: 25000
      coresMin: 4
```

That's bad. Cromwell doesn't pick up on the docker requirements, and submits jobs with no `-a` or `-q` parameters, causing the jobs to PEND indefinitely.  

They need to be reformatted into a single block like this:
```
requirements:
    - class: ResourceRequirement
      ramMin: 16000
      tmpdirMin: 25000
      coresMin: 4
    - class: DockerRequirement
      dockerPull: "mgibio/bisulfite"
```

I'm taking care of the rnaseq-pipeline cwls, but we need a systematic look through to find the rest.
