### ISSUE TITLE
insufficient requirements in qc_exome.cwl

### ISSUE THREAD

**Issue by tatahin** [genome/analysis-workflows#689]
Hello!
I tried to run alignment_exome.cwl  with BAMs and references from example_data/exome_workflow from repository.  But it failed with error:
```
[step collect_alignment_summary_metrics] completed success
[workflow qc] starting step collect_roi_hs_metrics
[step collect_roi_hs_metrics] Cannot make job: Workflow step contains valueFrom but StepInputExpressionRequirement not in requirements
[workflow qc] completed permanentFail
[step qc] completed permanentFail
[workflow ] completed permanentFail
```
So I added  "- class: StepInputExpressionRequirement" in qc_exome.cwl:
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow
label: "Exome QC workflow"
requirements:
    - class: SchemaDefRequirement
      types:
          - $import: ../types/labelled_file.yml
    - class: SubworkflowFeatureRequirement
    - class: StepInputExpressionRequirement
inputs:
    bam:
        type: File
        secondaryFiles: [^.bai]
    reference:
        type:
            - string
            - File
        secondaryFiles: [.fai, ^.dict]
    bait_intervals:
        type: File
    target_intervals:
<...>
```
and workflow was completed  successful.
